---

- include_task: install-redhat.yml
  when: ansible_os_family == 'RedHat'

- include_task: install-debian.yml
  when: ansible_os_family == 'Debian'

- include_task: virtual-users.yml
  when: vsftpd_enable_virt_users
